# -*- coding: utf-8 -*-
"""seqcoverage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zy646gaOaMBnoj7-Chq-07M_XIaOF6n
"""

#!/ usr/bin/env python3
import sys

if len(sys.argv) == 1:
    print("Syntax: " + sys.argv[0] + " file.sam genomelength")
    exit()

genome_length = int(sys.argv[2]) 
genome_change = [0]*genome_length # genome change is a list of integers all set to zero

sam_file = open(sys.argv[1]) # open sam file
for line in sam_file: # read each line into the variable "line"
    if line[0] != '@': # do the block below only if line doesn't start with @
        fields = line.split("\t")               # make list of tab-separated fields
        if ((int(fields[1]) & 4) == 0):         # flag indicates that the read maps
            start_position = int(fields[3])     # fields[3] is the map position
            end_position = start_position+ 100  # this is because reads are 100 bases
            genome_change[start_position] += 1  # increment start position by one
            genome_change[end_position] -= 1    # decrement end position by one

sam_file.close()

print("fixedStep chrom=genome start=1 step=1 span=1") # print track as a wiggle file
current_coverage = 0 

for position in range(genome_length): # cicle over all positions of the genome
    current_coverage = current_coverage + genome_change[position] 
    print(current_coverage)

